_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  announcements_feed: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_browser: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  image_captcha: 0
  inline_entity_form: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  login_destination: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quiz_maker: 0
  quiz_maker_results: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  state_machine: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  user_registrationpassword: 0
  views_bulk_operations: 0
  views_ui: 0
  views: 10
  standard: 1000
theme:
  claro: 0
  bootstrap_barrio: 0
profile: standard
